import "./globals.css";

import { Inter } from "next/font/google";
import Image from "next/image";

import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Assessment app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full px-12 py-6 flex justify-between bg-white shadow-lg fixed">
          <Image src="/next.svg" width={100} height={200} alt="logo"></Image>
        </div>
        {children}
      </body>
    </html>
  );
}
